/**
 * pregenerate.js - refill the offline pack from the model.
 *
 * The pack that ships is hand-authored so a fresh clone works with no API key.
 * Run this the night before the fair, on wifi you trust, to replace it with
 * real model output - then the offline path and the online path produce the
 * same flavour of structure and nobody can tell when the venue wifi dies.
 *
 *   npm run pregenerate                 # regenerate from the built-in prompts
 *   npm run pregenerate -- --merge      # keep existing structures, add new ones
 *
 * Roughly 40 Haiku calls with a ~250 token prompt and a ~120 token response:
 * a few cents, and you only do it once.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { normalizeStructure } from '../public/js/spec.js';
import { screen } from '../server/moderation.js';
import { generateStructure, describeError, isConfigured, MODEL } from '../server/claude.js';

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const target = path.join(root, 'public/data/fallback.json');

// Same as the server: load .env in code so this runs on Node 20 LTS too.
try {
  process.loadEnvFile(path.join(root, '.env'));
} catch {
  // No .env - main() reports the missing key and exits.
}

/**
 * Prompts chosen to cover what a crowd actually types at a park booth: rides,
 * architecture, creatures, food, and the generic "a statue of <someone>" that
 * every second person asks for.
 */
const PROMPTS = [
  'a statue', 'a statue of a person', 'a marble bust on a pedestal',
  'a ferris wheel', 'a carousel', 'a roller coaster', 'a big top circus tent',
  'a bouncy castle', 'a haunted house', 'a lighthouse', 'a clock tower',
  'a castle', 'a pyramid', 'a windmill', 'a giant robot', 'a dragon',
  'a dinosaur', 'a giant cat', 'a friendly monster', 'a rocket ship',
  'a UFO', 'a giant ice cream cone', 'a hot dog stand', 'a pizza slice',
  'a snack stand', 'a big tree', 'a cactus', 'a fountain', 'a wrecking ball',
  'an arcade cabinet', 'a vending machine', 'a school bus', 'a food truck',
  'a giant rubber duck', 'a treehouse', 'a water slide', 'a bandstand',
  'a scoreboard', 'a giant chess piece', 'a goofy little guy',
];

/** Keywords for the offline matcher, so "a ferris wheel" still finds the ferris wheel. */
const STOP_WORDS = new Set(['a', 'an', 'the', 'of', 'made', 'giant', 'big', 'little', 'friendly']);

function keywordsFor(prompt, label) {
  const words = `${prompt} ${label}`
    .toLowerCase()
    .split(/[^a-z]+/)
    .filter((word) => word.length > 2 && !STOP_WORDS.has(word));
  return [...new Set(words)];
}

async function main() {
  if (!isConfigured()) {
    console.error('No ANTHROPIC_API_KEY found. Copy .env.example to .env and add a key.');
    process.exit(1);
  }

  const merge = process.argv.includes('--merge');
  const existing = merge ? JSON.parse(fs.readFileSync(target, 'utf8')).structures : [];
  const structures = [...existing];
  let failures = 0;

  console.log(`Generating ${PROMPTS.length} structures with ${MODEL}...\n`);

  for (const prompt of PROMPTS) {
    try {
      const { structure } = await generateStructure(prompt);
      const normalized = normalizeStructure(structure);

      // The pack ships in the repo and plays unattended in attract mode, so
      // anything questionable is dropped rather than shipped.
      if (screen(normalized.label).blocked) {
        console.log(`  skip  ${prompt} -> label did not pass the blocklist`);
        continue;
      }

      structures.push({ keywords: keywordsFor(prompt, normalized.label), ...normalized });
      console.log(`  ok    ${prompt} -> ${normalized.label} (${normalized.parts.length} parts)`);
    } catch (err) {
      failures += 1;
      console.log(`  fail  ${prompt} -> ${describeError(err)}`);
    }
  }

  if (!structures.length) {
    console.error('\nNothing generated - leaving the existing pack alone.');
    process.exit(1);
  }

  fs.writeFileSync(
    target,
    `${JSON.stringify(
      {
        note: `Generated by scripts/pregenerate.js with ${MODEL} on ${new Date().toISOString().slice(0, 10)}.`,
        structures,
      },
      null,
      2,
    )}\n`,
  );

  console.log(`\nWrote ${structures.length} structures to public/data/fallback.json (${failures} failed).`);
  console.log('Run `npm test` to confirm they all survive normalization.');
}

main().catch((err) => {
  console.error(describeError(err));
  process.exit(1);
});
