/**
 * pregenerate.js - refill the offline pack from the model.
 *
 * The pack that ships is hand-authored so a fresh clone works with no API key.
 * Run this the night before the fair, on wifi you trust, to replace it with
 * real model output - then the offline path and the online path produce the
 * same flavour of object and nobody can tell when the venue wifi dies.
 *
 *   npm run pregenerate                 # regenerate from the built-in prompts
 *   npm run pregenerate -- --merge      # keep existing objects, add new ones
 *
 * Roughly 40 Haiku calls with a ~250 token prompt and a ~120 token response:
 * a few cents, and you only do it once.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { normalizeSpec } from '../public/js/spec.js';
import { screen } from '../server/moderation.js';
import { generateSpec, describeError, isConfigured, MODEL } from '../server/claude.js';

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const target = path.join(root, 'public/data/fallback.json');

/**
 * Prompts chosen to span the physical range - light and heavy, bouncy and dead,
 * huge and tiny - so the pack can answer most of what a crowd types.
 */
const PROMPTS = [
  'a bowling ball', 'a bowling ball made of jello', 'a trampoline', 'an anvil',
  'an anvil the size of a car', 'a grand piano', 'a rubber duck', 'a beach ball',
  'a brick', 'a helium balloon', 'a watermelon', 'a car', 'a refrigerator',
  'a slice of pizza', 'a cannonball', 'a feather', 'a cinder block',
  'a basketball', 'a sofa', 'a dumbbell', 'an ice cube', 'a wooden log',
  'a car tire', 'a bank safe', 'an egg', 'a marshmallow', 'a boulder',
  'a textbook', 'a traffic cone', 'a bale of hay', 'a superball', 'a pencil',
  'a donut', 'a bathtub', 'a stack of pancakes', 'a bouncy castle',
  'a shopping cart', 'a filing cabinet', 'a giant gummy bear', 'a wrecking ball',
];

/** Keywords for the offline matcher, so "a bowling ball" still finds the bowling ball. */
const STOP_WORDS = new Set(['a', 'an', 'the', 'of', 'made', 'giant', 'stack', 'bale']);

function keywordsFor(prompt, label) {
  const words = `${prompt} ${label}`
    .toLowerCase()
    .split(/[^a-z]+/)
    .filter((word) => word.length > 2 && !STOP_WORDS.has(word));
  return [...new Set(words)];
}

async function main() {
  if (!isConfigured()) {
    console.error('No ANTHROPIC_API_KEY found. Copy .env.example to .env and add a key.');
    process.exit(1);
  }

  const merge = process.argv.includes('--merge');
  const existing = merge ? JSON.parse(fs.readFileSync(target, 'utf8')).objects : [];
  const objects = [...existing];
  let failures = 0;

  console.log(`Generating ${PROMPTS.length} objects with ${MODEL}...\n`);

  for (const prompt of PROMPTS) {
    try {
      const { spec } = await generateSpec(prompt);
      const normalized = normalizeSpec(spec);

      // The pack ships in the repo and plays unattended in attract mode, so
      // anything questionable is dropped rather than shipped.
      if (screen(normalized.label).blocked) {
        console.log(`  skip  ${prompt} -> label did not pass the blocklist`);
        continue;
      }

      objects.push({ keywords: keywordsFor(prompt, normalized.label), ...normalized });
      console.log(`  ok    ${prompt} -> ${normalized.label} (${normalized.shape})`);
    } catch (err) {
      failures += 1;
      console.log(`  fail  ${prompt} -> ${describeError(err)}`);
    }
  }

  if (!objects.length) {
    console.error('\nNothing generated - leaving the existing pack alone.');
    process.exit(1);
  }

  fs.writeFileSync(
    target,
    `${JSON.stringify(
      {
        note: `Generated by scripts/pregenerate.js with ${MODEL} on ${new Date().toISOString().slice(0, 10)}.`,
        objects,
      },
      null,
      2,
    )}\n`,
  );

  console.log(`\nWrote ${objects.length} objects to public/data/fallback.json (${failures} failed).`);
  console.log('Run `npm test` to confirm they all survive normalization.');
}

main().catch((err) => {
  console.error(describeError(err));
  process.exit(1);
});
